#!/bin/bash

set -e
#set -x

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

USAGE="$0 [path to target project]"

PROJECT_DIR=$1
if [ -z "$PROJECT_DIR" ]; then
  echo "Please a path to the target project."
  echo $USAGE
  exit
fi

if [ ! -d "$PROJECT_DIR" ]; then
  echo "$PROJECT_DIR does not exist."
  echo $USAGE
  exit
fi

rsync -avz --stats --update $ROOT/config/ $PROJECT_DIR/config/
rsync -avz --stats --update $ROOT/docker/ $PROJECT_DIR/docker/
rsync -avz --stats --update $ROOT/scripts/ $PROJECT_DIR/scripts/
rsync -avz --stats --update $ROOT/container $PROJECT_DIR/container

# set the name
echo $(basename -- $PROJECT_DIR) | awk '{print tolower($0)}' > $PROJECT_DIR/config/name